#!/bin/sh

# usage: setvar <varname> <value>

if [ $# -lt 2 ]; then
    echo "Usage: $0 <varname> <value>"
    exit 1
fi

varname="$1"
shift
value="$*"

file="/tmp/hyprvar_${varname}"

printf "%s\n" "$value" > "$file"
