#!/bin/sh

OVERRIDE_FILE="$HOME/.config/.circadian-override"

if [ "$#" -ne 1 ] || { [ "$1" != "0" ] && [ "$1" != "1" ]; }; then
    echo "Usage: $0 <0|1>"
    exit 1
fi

if [ "$1" = "0" ]; then
    if [ -f "$OVERRIDE_FILE" ]; then
        rm "$OVERRIDE_FILE"
        echo "Deleted $OVERRIDE_FILE"
    else
        echo "$OVERRIDE_FILE does not exist."
    fi
else
    mkdir -p "$(dirname "$OVERRIDE_FILE")"
    touch "$OVERRIDE_FILE"
    echo "Created $OVERRIDE_FILE"
fi
